name: lhe maestro 

on:
  push:
    branches: [ Ainz-devs/OVL-MD-V2main ]
  pull_request:
    branches: [ Ainz-devs/OVL-MD-V2main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
